substitutions:
  devicename: Boti szoba redőny
  nyitasiIdoMinimum: 10
  nyitasiIdoMaximum: 30
  espHome_name: boti_szoba-redony
  ipCim: 192.168.22.232


esphome:
  name: ${espHome_name}
  friendly_name: ${devicename}
  on_boot:
   then:
     - lambda: |-
         id(shutter).set_open_duration((uint32_t)(id(up_time_s).state * 1000));
         id(shutter).set_close_duration((uint32_t)(id(down_time_s).state * 1000));

preferences:
  flash_write_interval: 5s     # mennyi időnként írja ki; 5–10s jó kompromisszum

globals:
  - id: moving_dir        #  1 = felfelé (open), -1 = lefelé (close), 0 = áll
    type: int
    restore_value: no
    initial_value: '0'

esp8266:
  board: esp01_1m
  restore_from_flash: true
# Enable logging
logger:


# Enable Home Assistant API
api:
  encryption:
    key: "WjzR8Y+6pzdFYieFLmUg5lj7bBEx20WgroVFVnQuWQ4="

ota:
  - platform: esphome
    password: "7bbea302f84ebf2611f529108f5fe9ce"


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: ${ipCim}
    gateway: 192.168.22.1
    subnet: 255.255.255.0
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${devicename}
    password: "SG9TQNv0qWXt"


captive_portal:


web_server:
  port: 80


i2c:
  sda: GPIO12
  scl: GPIO14


#################### SZENZOROK ####################
sensor:
  - platform: ade7953_i2c
    irq_pin: GPIO16 # Prevent overheating by setting this
    voltage:
      name: ${devicename} feszültség
    # On the Shelly 2.5 channels are mixed ch1=B ch2=A
    current_a:
      name: ${devicename} áram B
    current_b:
      name: ${devicename} áram A
    active_power_a:
      name: ${devicename} Aktív teljesítmény A
      # active_power_a is normal, so don't multiply by -1
    active_power_b:
      name: ${devicename} Aktív teljesítmény B
      # active_power_b is inverted, so take the absolute value
      filters:
        - lambda: return abs(x);
    update_interval: 60s

  # NTC Temperature
  - platform: ntc
    sensor: temp_resistance_reading
    name: ${devicename} Temperature
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    icon: "mdi:thermometer"
    calibration:
      b_constant: 3350
      reference_resistance: 10kOhm
      reference_temperature: 298.15K
  - platform: resistance
    id: temp_resistance_reading
    sensor: temp_analog_reading
    configuration: DOWNSTREAM
    resistor: 32kOhm
  - platform: adc
    id: temp_analog_reading
    pin: A0

status_led:
  pin:
    number: GPIO0
    inverted: yes


#################### BINÁRIS SZENZOROK ####################
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO13
    name: ${devicename} Switch1
    filters:
      - delayed_on: 20ms
    on_press:
      then:
        - if:              # ha már felfelé mozog: állj meg
            condition:
              lambda: 'return id(moving_dir) == 1;'
            then:
              - cover.stop: shutter
            else:
              - if:        # ha lefelé mozog: előbb állj meg, aztán fordulj
                  condition:
                    lambda: 'return id(moving_dir) == -1;'
                  then:
                    - cover.stop: shutter
                    - delay: 200ms
              - cover.open: shutter

  - platform: gpio
    pin:
      number: GPIO5
    name: ${devicename} Switch2
    filters:
      - delayed_on: 20ms
    on_press:
      then:
        - if:              # ha már lefelé mozog: állj meg
            condition:
              lambda: 'return id(moving_dir) == -1;'
            then:
              - cover.stop: shutter
            else:
              - if:        # ha felfelé mozog: előbb állj meg, aztán fordulj
                  condition:
                    lambda: 'return id(moving_dir) == 1;'
                  then:
                    - cover.stop: shutter
                    - delay: 200ms
              - cover.close: shutter




#################### SWITCH-EK ####################
switch:
  - platform: restart
    name: ${devicename} Restart
  - platform: gpio
    id: relay_up
    pin: GPIO4
    name: Relé fel
    restore_mode: RESTORE_DEFAULT_OFF
    interlock: [relay_up, relay_down]
    interlock_wait_time: 200ms
  - platform: gpio
    id: relay_down
    pin: GPIO15
    name: Relé le
    restore_mode: RESTORE_DEFAULT_OFF
    interlock: [relay_up, relay_down]
    interlock_wait_time: 200ms



#################### NUMBER ENTITÁSOK ####################
number:
  - platform: template
    name: "Redőny FEL idő (s)"
    id: up_time_s
    unit_of_measurement: "s"
    mode: BOX
    min_value: ${nyitasiIdoMinimum}
    max_value: ${nyitasiIdoMaximum}
    step: 0.1
    optimistic: true
    restore_value: true
    initial_value: 21
    set_action:
      - lambda: |-
          // x = a beállított érték (másodpercben)
          id(shutter).set_open_duration((uint32_t)(x * 1000));

  - platform: template
    name: "Redőny LE idő (s)"
    id: down_time_s
    unit_of_measurement: "s"
    mode: BOX
    min_value: ${nyitasiIdoMinimum}
    max_value: ${nyitasiIdoMaximum}
    step: 0.1
    optimistic: true
    restore_value: true
    initial_value: 20
    set_action:
      - lambda: |-
          id(shutter).set_close_duration((uint32_t)(x * 1000)); 
# induláskor is töltse be a számokból






#################### REDŐNY ####################
cover:
  - platform: time_based
    id: shutter
    name: "Redőny"
    manual_control: false
    open_action:
      - lambda: 'id(moving_dir) = 1;'
      - switch.turn_on: relay_up
    close_action:
      - lambda: 'id(moving_dir) = -1;'
      - switch.turn_on: relay_down
    stop_action:
      - switch.turn_off: relay_up
      - switch.turn_off: relay_down
      - lambda: 'id(moving_dir) = 0;'
    open_duration: 21s     # mérd le a valós idejét
    close_duration: 20s
