esphome:
  name: medence-futes-szivattyu-dugalj
  friendly_name: "Medence fűtés szivattyú dugalj"

esp8266:
  board: esp01_1m
  restore_from_flash: true

preferences:
  flash_write_interval: 5min

logger:

api:
  encryption:
    key: "7lQeojZckryLmVcu/nvXw08FSsLWg9aa5T4825lLvg8="

ota:
  - platform: esphome
    password: "e1e3b804b2a0680792c30f4ce301ba18"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.22.247
    gateway: 192.168.22.1
    subnet: 255.255.255.0

  ap:
    ssid: "Medence-Futes-Szivattyu-Dugalj"
    password: "Sph39HwCML5Z"

captive_portal:

web_server:
  port: 80

time:
  - platform: homeassistant
    id: homeassistant_time

substitutions:
  device_name: "Medence fűtés szivattyú dugalj"

  # BlitzWolf BW-SHP6 15A, 2020 / újabb verzió
  current_res: "0.00117"
  voltage_div: "755"
  max_power: "3450"
  cf1_pin: GPIO04

binary_sensor:
  - platform: gpio
    name: "${device_name} gomb"
    id: button
    pin:
      number: GPIO13
      inverted: true
    on_press:
      then:
        - switch.toggle: relay

output:
  - platform: gpio
    pin: GPIO0
    inverted: true
    id: led

switch:
  - platform: gpio
    pin: GPIO15
    restore_mode: RESTORE_DEFAULT_ON
    id: relay
    name: "${device_name} relé"
    on_turn_on:
      - output.turn_on: led
    on_turn_off:
      - output.turn_off: led

status_led:
  pin:
    number: GPIO2
    inverted: true

sensor:
  - platform: hlw8012
    sel_pin:
      number: GPIO12
      inverted: true
    cf_pin: GPIO05
    cf1_pin: ${cf1_pin}
    current_resistor: ${current_res}
    voltage_divider: ${voltage_div}

    current:
      name: "${device_name} áram"
      unit_of_measurement: "A"
      accuracy_decimals: 3
      icon: mdi:flash-outline
      force_update: true

    voltage:
      name: "${device_name} feszültség"
      unit_of_measurement: "V"
      accuracy_decimals: 1
      icon: mdi:flash-outline
      force_update: true

    power:
      name: "${device_name} teljesítmény"
      unit_of_measurement: "W"
      accuracy_decimals: 1
      id: power
      icon: mdi:flash-outline
      force_update: true
      on_value_range:
        - above: ${max_power}
          then:
            - output.turn_off: led
            - switch.turn_off: relay

    change_mode_every: 4
    update_interval: 10s

  - platform: total_daily_energy
    name: "${device_name} napi fogyasztás"
    power_id: power
    unit_of_measurement: "kWh"
    accuracy_decimals: 5
    filters:
      - multiply: 0.001